### ISSUE TITLE
Multipal Hub Support  

### ISSUE THREAD

**Issue by EnigmaFx** [KraigM/homebridge-harmonyhub#18] opened 2016-01-04 23:54 UTC
Hi I Have 3 hubs in my home? it seems that this plugin only supports one hub? is there a work around for this by chance? "

**Comment by KraigM** [comment] 2016-01-05 00:09
Duplicate of #6

**Closed by KraigM** 2016-01-05 00:09 UTC
Labels: duplicate

**Comment by EnigmaFx** [comment] 2016-01-05 03:50
(UPDATE) Just manually assign an ip and a different name to each hub and it works with out a hitch Confirmed and tested --->  http://d.pr/i/17Jb9

**Comment by EnigmaFx** [comment] 2016-01-05 03:52
FYI The config File chould look something like this ---> http://d.pr/i/fyNE <---
